# Generated by Django 4.2.7 on 2024-02-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactbook_app', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.CharField(choices=[('general', '一般ユーザー'), ('admin', '特権ユーザー')], default='general', max_length=10),
        ),
    ]
