# Generated by Django 4.2.7 on 2024-02-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_remove_event_id_event_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
